name: RF Childcare
title: RF Childcare - OFSTED Registered Child Minders in Leeds
description: RF Childcare is an OFSTED registered childminders in the LS27 area, with childcare experience since 2005.
host: 0.0.0.0

repository: cmbuckley/rfchildcareleeds.co.uk
url: https://rfchildcareleeds.co.uk
baseurl: ""

markdown: kramdown
highlighter: rouge

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-redirect-from

sass:
  style: compressed

facebook_app_id: 341096436539165
social:
  instagram: rebecca.firthchildminding
  linkedin: rebecca-firth-aaa196184
